@linkedin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjNmYTQwNmRkOWJmNDJlNWZmYjU5YyIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibW96YWtrLmlvIiwiZmlyc3RfbmFtZSI6Ik1vaGFtbWVkIiwibGFzdF9uYW1lIjoiWmFrYXJpYSIsImF2YXRhciI6Imh0dHBzOi8vbWVkaWEubGljZG4uY29tL2Rtcy9pbWFnZS92Mi9ENEUwM0FRRXNjR3hvUmJnT0F3L3Byb2ZpbGUtZGlzcGxheXBob3RvLXNocmlua184MDBfODAwL0I0RVpQb3NHajZIc0FjLS8wLzE3MzQ3NzU2OTU5MTA_ZT0xNzUyNzEwNDAwJnY9YmV0YSZ0PVdYbEExRGJlZDJQalotUTAyUkYzQlBfX3RQVVFOWmZVSDVkbElkVUF5NFUiLCJpYXQiOjE3NDcwNDMzMjksImV4cCI6MTc0NzY0ODEyOX0.gAfdj9lNnBIUlPAqX5H-NJUlHLIjQ8d_W82l8FUp0DU
@google_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjNmYTk4NmRkOWJmNDJlNWZmYjVhMiIsImVtYWlsIjoidWcyNDI0Nzg3QGluZXMuYWMucnciLCJ1c2VybmFtZSI6InVnMjQyNDc4NyIsImZpcnN0X25hbWUiOiJNT0hBTUVEIEFITUVEIiwibGFzdF9uYW1lIjoiTW9tYWhlZCBaYWthcmlhIiwiYXZhdGFyIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSmtDanZtMkh5QTdkX1VfRjhrTG0zT0JFREN2OE9ERy1KcnZCb3JxR2lJWFBCZmxRPXM5Ni1jIiwiaWF0IjoxNzQ1NjgxNzEzLCJleHAiOjE3NDYyODY1MTN9.LZubYerEqB2_QxDrngpXH6YkKZzfF-m_Y849PS4Kx2c

@gorwanda_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjFjNDllNmI3MTM1ODkwNTFjYmI1MSIsImVtYWlsIjoiZ29yd2FuZGE3NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImdvcndhbmRhNzQiLCJmaXJzdF9uYW1lIjoiR28iLCJsYXN0X25hbWUiOiJSd2FuZGEiLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMTkR0d2dDSHVPUVRsSXJFYjUxUFd3RHhvMk5pX0ltc0djM015TWZYWjNodThKQUE9czk2LWMiLCJpYXQiOjE3NTUzMzMzNDksImV4cCI6MTc1NTkzODE0OX0.g1ONpKAFZAXiVdgI3QrWqA9P8nLMTTdl5TLkfgaT9fk

@linkedin_team_id = 955c7caa-fc27-48dd-b8aa-4c33b258f311

@google_team_id = a0f6adf1-7e32-47c1-95f1-b8480f94cf49




### invite user
POST http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/members/invitations
Content-Type: application/json
Authorization: Bearer {{gorwanda_token}}

{
    "email" : "ug2424787@ines.ac.rw",
    "role" : "editor"
}

### 





@invitations_id = 680a76958b4c2381b6ce7a54
### cancel invitation
GET  http://127.0.0.1:3000/api/teams/{{google_team_id}}/members/invitations/{{invitations_id}}
Authorization: Bearer {{google_token}}


### list team members
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/members
Authorization: Bearer {{linkedin_token}}


@member_id = 67f3fa406dd9bf42e5ffb59c
### change member role
PUT http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/members/{{member_id}}
Authorization: Bearer {{linkedin_token}}
Content-Type: application/json

{
    "role" : "co-leader"
}



### leave team
GET http://127.0.0.1:3000/api/teams/{{google_team_id}}/leave
Authorization: Bearer {{linkedin_token}}



### kick team member
GET http://127.0.0.1:3000/api/teams/{{google_team_id}}/members/67f3fa406dd9bf42e5ffb59c/kick
Authorization: Bearer {{google_token}}





//join team functionality

### join team
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/join
Authorization: Bearer {{google_token}}


### list join requests
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/join-requests
Authorization: Bearer {{linkedin_token}}


### accept join requests
POST http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/join-requests/68110c92bd8e49d67c50b7d1
Authorization: Bearer {{linkedin_token}}
Content-Type: application/json

{
    "role" : "co-leader"
}


### reject join requests
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/join-requests/680fb5cc0aa4d144342b63ad
Authorization: Bearer {{linkedin_token}}




### create direct join link
POST http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/direct-join-link
Authorization: Bearer {{linkedin_token}}
Content-Type: application/json

{
    "role" : "viewer"
}


### join With Direct JoinLink
GET http://127.0.0.1:3000/api/teams/67ff830705b16d1c9a118f60/direct-join-link?token=f1bdbf64-aa6b-42e5-9af4-6bd386b5b5cc
Authorization: Bearer {{gorwanda_token}}