@linkedin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjNmYTQwNmRkOWJmNDJlNWZmYjU5YyIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibW96YWtrLmlvIiwiZmlyc3RfbmFtZSI6Ik1vaGFtbWVkIiwibGFzdF9uYW1lIjoiWmFrYXJpYSIsImF2YXRhciI6Imh0dHBzOi8vbWVkaWEubGljZG4uY29tL2Rtcy9pbWFnZS92Mi9ENEUwM0FRRXNjR3hvUmJnT0F3L3Byb2ZpbGUtZGlzcGxheXBob3RvLXNocmlua184MDBfODAwL0I0RVpQb3NHajZIc0FjLS8wLzE3MzQ3NzU2OTU5MTA_ZT0xNzUwMjkxMjAwJnY9YmV0YSZ0PWd6Ri05LUZOQ2g3UmlacTFTMGtVcklMVm51TUg4NFFSQWpMRkJyTzdzT1UiLCJpYXQiOjE3NDUwNTE4MzMsImV4cCI6MTc0NTY1NjYzM30.1WBX-ConbyhKCs3n-iHPqRrTMbIAhWUlA8kIIcYshw8
@google_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjNmYTk4NmRkOWJmNDJlNWZmYjVhMiIsImVtYWlsIjoidWcyNDI0Nzg3QGluZXMuYWMucnciLCJ1c2VybmFtZSI6InVnMjQyNDc4NyIsImZpcnN0X25hbWUiOiJNT0hBTUVEIEFITUVEIiwibGFzdF9uYW1lIjoiTW9tYWhlZCBaYWthcmlhIiwiYXZhdGFyIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSmtDanZtMkh5QTdkX1VfRjhrTG0zT0JFREN2OE9ERy1KcnZCb3JxR2lJWFBCZmxRPXM5Ni1jIiwiaWF0IjoxNzQ1MTY4NzAzLCJleHAiOjE3NDU3NzM1MDN9.Shsu-W440wuXzHUo2gpNlUU6ecuJeKPgBj_Km0oqeEc

@linkedin_team_id = 955c7caa-fc27-48dd-b8aa-4c33b258f311

@google_team_id = a0f6adf1-7e32-47c1-95f1-b8480f94cf49




### invite user
POST http://127.0.0.1:3000/api/teams/{{google_team_id}}/members/invitations
Content-Type: application/json
Authorization: Bearer {{google_token}}

{
    "email" : "mozakk.io@gmail.com",
    "role" : "co-leader"
}


### accept invitation
GET http://127.0.0.1:3000/api/teams/68037e1d65205a28c106e45f/members/accept-invitation?token=dda1822c-b6fe-46ca-a4b3-762a46451d52
Authorization: Bearer {{google_token}}



### list team invitations
GET http://127.0.0.1:3000/api/teams/{{google_team_id}}/members/invitations?status=rejected
Authorization: Bearer {{google_token}}



@invitations_id = 680a76958b4c2381b6ce7a54
### cancel invitation
GET  http://127.0.0.1:3000/api/teams/{{google_team_id}}/members/invitations/{{invitations_id}}
Authorization: Bearer {{google_token}}


### list team members
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/members
Authorization: Bearer {{linkedin_token}}


@member_id = 67f3fa406dd9bf42e5ffb59c
### change member role
PUT http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/members/{{member_id}}
Authorization: Bearer {{linkedin_token}}
Content-Type: application/json

{
    "role" : "co-leader"
}



### leave team
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/leave
Authorization: Bearer {{google_token}}



### kick team member
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/members/67f3fa986dd9bf42e5ffb5a2/kick
Authorization: Bearer {{linkedin_token}}