//tokens
@linkedin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjNmYTQwNmRkOWJmNDJlNWZmYjU5YyIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibW96YWtrLmlvIiwiZmlyc3RfbmFtZSI6Ik1vaGFtbWVkIiwibGFzdF9uYW1lIjoiWmFrYXJpYSIsImF2YXRhciI6Imh0dHBzOi8vbWVkaWEubGljZG4uY29tL2Rtcy9pbWFnZS92Mi9ENEUwM0FRRXNjR3hvUmJnT0F3L3Byb2ZpbGUtZGlzcGxheXBob3RvLXNocmlua184MDBfODAwL0I0RVpQb3NHajZIc0FjLS8wLzE3MzQ3NzU2OTU5MTA_ZT0xNzUzOTIwMDAwJnY9YmV0YSZ0PUppSlkxRXI5dkpWWmFSdnc1ZUpKMk1HRFRHeXlneFdwMGZ4T1JHQmQtMk0iLCJpYXQiOjE3NDgzNjE4ODUsImV4cCI6MTc0ODk2NjY4NX0.j7nwEnmXeHcLP5EUubD-UQ3OjUINs_iwXST3FiWIHjE
@google_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjNmYTk4NmRkOWJmNDJlNWZmYjVhMiIsImVtYWlsIjoidWcyNDI0Nzg3QGluZXMuYWMucnciLCJ1c2VybmFtZSI6InVnMjQyNDc4NyIsImZpcnN0X25hbWUiOiJNT0hBTUVEIEFITUVEIiwibGFzdF9uYW1lIjoiTW9tYWhlZCBaYWthcmlhIiwiYXZhdGFyIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSmtDanZtMkh5QTdkX1VfRjhrTG0zT0JFREN2OE9ERy1KcnZCb3JxR2lJWFBCZmxRPXM5Ni1jIiwiaWF0IjoxNzQ3NDc1NzM0LCJleHAiOjE3NDgwODA1MzR9.OCs3fnJrRSznBrt1H_yknQVNz4Afk5l9E1w2dQVouTc

@gorwanda_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjFjNDllNmI3MTM1ODkwNTFjYmI1MSIsImVtYWlsIjoiZ29yd2FuZGE3NEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImdvcndhbmRhNzQiLCJmaXJzdF9uYW1lIjoiR28iLCJsYXN0X25hbWUiOiJSd2FuZGEiLCJhdmF0YXIiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMTkR0d2dDSHVPUVRsSXJFYjUxUFd3RHhvMk5pX0ltc0djM015TWZYWjNodThKQUE9czk2LWMiLCJpYXQiOjE3NDc0NzYwMzgsImV4cCI6MTc0ODA4MDgzOH0.O-V9S3PPXoEybqrGp2H5eqhYFUnaH72oq6bAcG9K-d8


//teams
@linkedin_team_id = 955c7caa-fc27-48dd-b8aa-4c33b258f311

@google_team_id = a0f6adf1-7e32-47c1-95f1-b8480f94cf49






//basic features
### create resource 
POST http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/resources
Content-Type: application/json
Authorization: Bearer {{linkedin_token}}

{
    "type" : "codebase",
    "name": "python project",
    "language": "python"

}


### get single resource
GET http://127.0.0.1:3000/api/teams/{{google_team_id}}/resources/682995d3a5ef77b61a944c1d
Authorization: Bearer {{linkedin_token}}



### get all resources
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/resources
Authorization: Bearer {{linkedin_token}}



### delete resources
DELETE  http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/resources/68299fb2bf950285f2af6db0
Authorization: Bearer {{google_token}}



### update resource 
PATCH  http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/resources/6829a34486fee0d400f576e1
Content-Type: application/json
Authorization: Bearer {{gorwanda_token}}

{
    "type" : "document"
}



### get my resources
GET http://127.0.0.1:3000/api/teams/{{linkedin_team_id}}/resources/my
Authorization: Bearer {{gorwanda_token}}