###register 
POST http://127.0.0.1:3000/api/auth/register
Content-Type: application/json

{
    "username": "zakk",
    "email" : "mozakk.io@gmail.com",
    "password": "testpassU24ord",
    "first_name": "Test",
    "last_name": "User"
}


###email verify
GET http://127.0.0.1:3000/api/auth/email-verify/d3fa109c-8ea5-44ab-9d8c-74dd4f574459


### login user
POST http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
    "email" : "mozakk.io@gmail.com",
    "password": "testpassU24ord"
}


### login user
GET http://127.0.0.1:3000/api/auth/logout

